<?php
$newUser=new Users();
?>
<?php $this->start('head');?>
<?php $this->setSiteTitle('Privacy Policy | Broombids');?>
<style type="text/css">
    .animate-ball .ball
    {
        background: #2cc1d64f !important;
    }
  
</style>
<?php $this->end();?>

<?php $this->start('body');?>
<section class="page-banner">
    <div class="container">
        <div class="page-title-wrapper">
            <h1 class="page-title">Privacy Policy</h1>
            <ul class="bradcurmed">
                <li><a href="<?=PROOT?>" rel="noopener noreferrer">Home</a></li>
                <li>Privacy Policy</li>
            </ul>
        </div>
    </div>
    
    <ul class="animate-ball">
        <li class="ball"></li>
        <li class="ball"></li>
        <li class="ball"></li>
        <li class="ball"></li>
        <li class="ball"></li>
    </ul>
</section>

<section class="portfolio-single">
    <div class="container">
        <div class="portfolio-single-wrapper">
           
            <div class="portfolio-content">                
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <h3 class="sub-title">A. Introduction.</h3>
                            <ol>
                                <li>The privacy of our website visitors is very important to us and we are committed to  safeguarding it. This policy explains what we will do with your personal information. </li>
                                <li>Accepting the use of cookies in accordance with the terms of this policy, when you visit our website for the first time, allows us to use cookies every time you visit our website.</li>
                                <li>The creation of this document is governed by both the Greek criminal law and the European and International conventions, instructions and regulations on the use of protection and preservation of personal data, and its acceptance means and limits the unconditional acceptance of all the following detailed details</li>
                            </ol>
                            <h3 class="sub-title">B. Collection of personal information.</h3>
                            <p>The following types of personal information may be collected, stored and used:</p>
                            <ol>
                                <li>information about your computer, including IP address, geolocation, type and version of browser and operating system.</li>
                                <li>information about visits and use of this site, including referral source, visit duration,page views, and site navigation paths.</li>
                                <li>information, such as the email address you enter when you register on our site.</li>
                                <li>information you enter when creating a profile on our website - for example, your  first name, last name, Tax Identification Number (TIN) and telephone and  employment details.</li>
                                <li>information such as the name and email address you enter to subscribe to emails and / or newsletters.</li>
                                <li>information you enter when using the services on our website.</li>
                                <li>the information generated by the use of our website, including when, how often and under what circumstances you use it.</li>
                                <li>information about anything you may buy, services you use or transactions you may make through our website, which includes your name, address, phone umber, email address and credit card details.</li>
                                <li>the information you publish on our website for the purpose of publishing it on the  internet, which includes your username, profile pictures and the content of your posts.</li>
                                <li>information contained in any communication you send us via email or through our website, including communication content and broadcasts.</li>
                                <li>any other personal information you send us. Before disclosing any other person's personal information to us, you must obtain the consent of that person to both disclose and process such personal data in accordance with this policy.</li>
                            </ol>
                            <h3 class="sub-title">C. Using your personal information.</h3>
                            <p>The personal information we submit through our website will be used for the purposes set out in this policy or on the relevant pages of the website. We may use your personal information for the following:</p>
                            <ol>
                                <li>the management of our website and business.</li>
                                <li>customizing our website for you.</li>
                                <li>allowing the use of the services available on our site. </li>
                                <li>provision of services that may be offered for purchase through our website</li>
                                <li>Send email notifications that you have specifically requested. </li>
                                <li>sending our newsletter by email, if you have requested it (you can let us know at any time if you no longer need the newsletter).</li>
                                <li>We send you marketing announcements about our business or the third-party businesses we choose carefully, which we believe may be of interest to you, by mail or, if you have specifically agreed to it, by e-mail or similar technology (you can let us</li>
                                <li>providing third parties with statistical information about our users (but such third parties will not be able to identify any individual user of this information or obtain any form of personal information other than that commonly shared in any document the website).</li>
                                <li>deals with inquiries and complaints made by you or about you about our site. </li>
                                <li>keeping our website safe and preventing fraud</li>
                                <li>verification of compliance with the terms and conditions governing the use of our website (including monitoring of private messages sent through our private messaging service). And</li>
                                <li>other uses. </li>
                            </ol>
                            <p>If you submit personal information for publication on our website, we will post and otherwise use this information in accordance with your permission.know any moment if you no longer need marketing communications).</p>
                            <p>Privacy settings can be used to restrict the posting of your information on our site and can be customized using the site's privacy controls. We will not provide, without your explicit consent, your personal information to third parties for the direct marketing of the third party.</p>

                            <h3 class="sub-title">D. The disclosure of personal information.</h3>
                            <p>We may disclose your personal information to any of our employees, officers, insurers, professional advisers, agents, as is reasonably necessary for the purposes set out in this policy, as well as to the security authorities, prosecutors or other public audit authorities if this is formally and legally requested of us. We may disclose your personal information to any member of our team (this means that our affiliates, our ultimate portfolio company and all its affiliates) are reasonably necessary for the purposes set out in this policy.</p>

                            <b>We can reveal your personal information:</b>

                            <ol>
                                <li>to the extent required by law to do so. </li>
                                <li>in relation to any current or future legal proceedings. </li>
                                <li>to establish, exercise or defend our legal rights (including providing information to third parties to prevent fraud and reduce credit risk).</li>
                                <li>to the buyer (or prospective buyer) of any business or asset we are (or intend to sell); and </li>
                                <li>to any person we reasonably believe may apply to a court or other competent authority for the disclosure of such personal information when, in our reasonable opinion, that court or authority would reasonably order that such disclosure be disclosed; information. Except as provided in this policy, we will not provide your personal information to third parties</li>                                
                            </ol>

                            <h3 class="sub-title">E. International data transfers.</h3>
                            <p>The information we collect may be stored, processed and transferred between the countries in which we operate, so that we may use the information in accordance with this policy. The information we collect can be transferred to the following countries that do not have data protection laws equivalent to those in force in the European Economic Area: the United States, Russia, Japan, China and India. Personal information you post on our site or submit for posting on our site may be available online worldwide. We cannot prevent the use or misuse of this information by others. You expressly agree to the transfer of personal information described in this section F.</p>

                            <h3 class="sub-title">F. Retention of personal information </h3>
                            <p>This section sets out data retention policies and procedures designed to ensure that they comply with our legal obligations regarding the retention and deletion of personal information. The personal information we process for any purpose or purposes is not stored for more than what is necessary for that purpose or purposes. Without prejudice to Article D-2, we will usually delete personal data that falls into the following categories at the date / time specified below: the personal data type will be deleted {ENTER DATE / TIME}. and {ENTER ADDITIONAL DATES / TIMES}.</p>
                        </div>
                    </div>
                    
                </div>
            </div>            
        </div>
    </div>
</section>



<?php $this->end();?>

